# -*- coding: utf-8 -*-
"""FOOD REGCONITION.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WRrsIX2nHjOXpF-YfXS2s1DqV-7e6IoF
"""

from google.colab import drive
import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator

# 1. Kết nối với Google Drive
drive.mount('/content/drive')

# 2. Đường dẫn chính xác dựa trên ảnh bạn cung cấp
data_dir = '/content/drive/MyDrive/FOOD RECO/FOOD'

print("\n=== ĐANG CHUẨN BỊ DỮ LIỆU ===")
# 3. Cấu hình Data Augmentation (Tăng cường dữ liệu để chống học vẹt)
datagen = ImageDataGenerator(
    rescale=1./255,          # Chuẩn hóa pixel về [0, 1]
    validation_split=0.2,    # Dành 20% dữ liệu để kiểm thử (Validation)
    rotation_range=20,       # Xoay ảnh
    width_shift_range=0.1,   # Dịch ngang
    height_shift_range=0.1,  # Dịch dọc
    zoom_range=0.1,          # Phóng to/thu nhỏ
    horizontal_flip=True     # Lật ngang
)

# 4. Tạo luồng dữ liệu Huấn luyện (Train)
train_generator = datagen.flow_from_directory(
    data_dir,
    target_size=(200, 200),  # Resize ảnh về 200x200
    batch_size=32,
    class_mode='categorical',
    subset='training',
    shuffle=True
)

# 5. Tạo luồng dữ liệu Kiểm thử (Validation)
val_generator = datagen.flow_from_directory(
    data_dir,
    target_size=(200, 200),
    batch_size=32,
    class_mode='categorical',
    subset='validation',
    shuffle=False
)

# Lưu lại danh sách nhãn tự động sinh ra từ tên thư mục
class_names = list(train_generator.class_indices.keys())
print("\nCác món ăn mô hình sẽ học:", class_names)

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense, Dropout

model = Sequential([
    # Lớp trích xuất đặc trưng 1
    Conv2D(32, (3, 3), activation='relu', input_shape=(200, 200, 3)),
    MaxPooling2D(2, 2),

    # Lớp trích xuất đặc trưng 2
    Conv2D(64, (3, 3), activation='relu'),
    MaxPooling2D(2, 2),

    # Lớp trích xuất đặc trưng 3
    Conv2D(128, (3, 3), activation='relu'),
    MaxPooling2D(2, 2),

    # Lớp trích xuất đặc trưng 4
    Conv2D(128, (3, 3), activation='relu'),
    MaxPooling2D(2, 2),

    # Làm phẳng dữ liệu
    Flatten(),

    # Lớp ẩn nơ-ron
    Dense(512, activation='relu'),
    Dropout(0.5), # Tắt 50% nơ-ron ngẫu nhiên để chống Overfitting

    # Lớp đầu ra (5 nơ-ron tương ứng 5 món, dùng softmax tính xác suất)
    Dense(5, activation='softmax')
])

model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

model.summary()

print("=== BẮT ĐẦU HUẤN LUYỆN (KHÔNG DÙNG EARLY STOPPING) ===")

# Tiến hành huấn luyện cạn 50 vòng
history = model.fit(
    train_generator,
    epochs=50,
    validation_data=val_generator
)

print(" Đã huấn luyện xong toàn bộ 50 Epochs!")

import matplotlib.pyplot as plt
import shutil

# 1. Vẽ biểu đồ Độ chính xác và Hàm mất mát
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(14, 5))

ax1.plot(history.history['accuracy'], label='Train Accuracy')
ax1.plot(history.history['val_accuracy'], label='Validation Accuracy')
ax1.set_title('Đồ thị Độ chính xác')
ax1.legend()

ax2.plot(history.history['loss'], label='Train Loss')
ax2.plot(history.history['val_loss'], label='Validation Loss')
ax2.set_title('Đồ thị Hàm mất mát (Loss)')
ax2.legend()

plt.show()

# 2. Lưu mô hình vào thẳng thư mục FOOD RECO trên Drive của bạn
# Ensure the path is correct for your Google Drive setup
model_save_path = '/content/drive/MyDrive/FOOD RECO/nhan_dien_mon_an.h5'
model.save(model_save_path)
print(f"Mô hình đã được lưu tại: {model_save_path}")

from tensorflow.keras.models import load_model

# Define the path where the model was saved in Google Drive
model_load_path = '/content/nhan_dien_mon_an (1).h5'

# Load the trained model
model = load_model(model_load_path)

# Make sure the class_names are consistent with training
# These were printed by the train_generator in cell 3wDbhLE_hDjz
class_names = ['Banh Mi', 'Bun', 'Com Tam', 'Pho', 'Xoi']

print("Mô hình đã được tải thành công!")
print("Các lớp dự đoán:", class_names)

import numpy as np
import matplotlib.pyplot as plt
from tensorflow.keras.preprocessing import image

# 1. ĐIỀN ĐƯỜNG DẪN ẢNH CỦA BẠN VÀO ĐÂY
# (Mẹo: Kéo thả ảnh vào thanh file bên trái Colab -> Click 3 dấu chấm ở file ảnh -> Chọn "Copy path" rồi dán vào đây)
duong_dan_anh = '/content/bbh.jpeg'

# 2. Danh sách 5 món ăn xếp theo thứ tự ABC (đảm bảo khớp với thư mục lúc train)
class_names = ['banh_mi', 'bun_bo', 'com_tam', 'pho', 'xoi']

try:
    # 3. Tải và xử lý ảnh về kích thước 200x200
    img = image.load_img(duong_dan_anh, target_size=(200, 200))
    x = image.img_to_array(img)
    x = np.expand_dims(x, axis=0)
    x = x / 255.0  # Chuẩn hóa chia 255

    # 4. Dự đoán sử dụng mô hình 'model' đang chạy trong bộ nhớ
    predictions = model.predict(x)
    class_idx = np.argmax(predictions)
    confidence = np.max(predictions) * 100

    # 5. Hiển thị kết quả trực quan
    plt.imshow(img)
    plt.title(f"Du doan: {class_names[class_idx]} ({confidence:.2f}%)")
    plt.axis('off')
    plt.show()

except Exception as e:
    print(f"Lỗi: Không tìm thấy hoặc không đọc được file ảnh tại '{duong_dan_anh}'. Hãy kiểm tra lại đường dẫn! Chi tiết: {e}")