# -*- coding: utf-8 -*-
"""Palm_CNN_Sequential_v3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1soE8NuL0Lgqi0RPd1U5yEp7fVxmIO6JM

## 📦 BƯỚC 1 — Cài thư viện
"""

!pip install roboflow -q

import tensorflow as tf
print('✅ TensorFlow:', tf.__version__)
print('🖥️  GPU:', tf.config.list_physical_devices('GPU') or '❌ Không có — hãy bật T4!')

"""## 📥 BƯỚC 2 — Tải Dataset từ Roboflow (format COCO)

> Vào [app.roboflow.com](https://app.roboflow.com) → Settings → **Roboflow API** → Copy key
"""

from roboflow import Roboflow
import os, json
from pathlib import Path

# ⚠️ DÁN API KEY CỦA BẠN VÀO ĐÂY
API_KEY = "RV5WOXnjJx2MNTUJ1kQQ"

rf      = Roboflow(api_key=API_KEY)
project = rf.workspace("dstu-dfliv").project("palm-lines-recognition")

# Dataset keypoint-detection → dùng format COCO
dataset     = project.version(10).download("coco")
DATASET_DIR = Path(dataset.location)
print(f"✅ Dataset tải về: {DATASET_DIR}")

# Kiểm tra cấu trúc
for p in sorted(DATASET_DIR.rglob('*.json')):
    print(f"  📄 {p.relative_to(DATASET_DIR)}")

"""## 🔨 BƯỚC 3 — Parse COCO annotation → Tạo tập classification

Dataset gốc là **keypoint-detection** → mỗi annotation có `category_id` (loại đường chỉ) và bounding box.  
Ta sẽ **crop từng vùng bbox** ra thành ảnh riêng, gán nhãn theo category → dùng train CNN classification.
"""

import json, shutil
import numpy as np
from PIL import Image
from pathlib import Path
from collections import defaultdict

OUTPUT_DIR = Path('/content/palm_classification')

def parse_coco_and_crop(split: str):
    """
    Đọc COCO annotation của split (train/valid/test),
    crop từng bbox ra, lưu vào OUTPUT_DIR/<split>/<class_name>/<img>.jpg
    """
    # Tìm file annotation JSON
    ann_file = DATASET_DIR / split / '_annotations.coco.json'
    img_dir  = DATASET_DIR / split
    if not ann_file.exists():
        print(f"  ⚠️  Không tìm thấy {ann_file}")
        return {}

    with open(ann_file) as f:
        coco = json.load(f)

    # Map id → tên class
    cat_map  = {c['id']: c['name'] for c in coco['categories']}
    # Map image_id → file_name
    img_map  = {i['id']: i['file_name'] for i in coco['images']}

    counts   = defaultdict(int)
    skipped  = 0

    for ann in coco['annotations']:
        img_id   = ann['image_id']
        cat_id   = ann['category_id']
        cat_name = cat_map.get(cat_id, f'class_{cat_id}')
        fname    = img_map.get(img_id)
        if fname is None:
            skipped += 1
            continue

        img_path = img_dir / fname
        if not img_path.exists():
            skipped += 1
            continue

        # COCO bbox: [x, y, w, h]
        bbox = ann.get('bbox')
        try:
            img = Image.open(img_path).convert('RGB')
            W, H = img.size

            if bbox and len(bbox) == 4 and bbox[2] > 10 and bbox[3] > 10:
                x, y, bw, bh = bbox
                # Thêm padding 10%
                pad = 0.10
                x1  = max(0,  int(x  - bw * pad))
                y1  = max(0,  int(y  - bh * pad))
                x2  = min(W,  int(x  + bw + bw * pad))
                y2  = min(H,  int(y  + bh + bh * pad))
                crop = img.crop((x1, y1, x2, y2))
            else:
                # Không có bbox hợp lệ → dùng cả ảnh
                crop = img

            # Lưu
            save_dir = OUTPUT_DIR / split / cat_name
            save_dir.mkdir(parents=True, exist_ok=True)
            out_name = f"{img_path.stem}_ann{ann['id']}.jpg"
            crop.save(save_dir / out_name, quality=92)
            counts[cat_name] += 1

        except Exception as e:
            skipped += 1

    print(f"  [{split}] Đã crop: {dict(counts)}  | Bỏ qua: {skipped}")
    return dict(counts)


# Reset output
if OUTPUT_DIR.exists():
    shutil.rmtree(OUTPUT_DIR)

print("🔨 Đang parse & crop bounding boxes...")
for split in ['train', 'valid', 'test']:
    parse_coco_and_crop(split)

# Lấy danh sách class
CLASS_NAMES = sorted([d.name for d in (OUTPUT_DIR / 'train').iterdir() if d.is_dir()])
NUM_CLASSES  = len(CLASS_NAMES)
print(f"\n✅ Xong! Số class: {NUM_CLASSES}")
print(f"🏷️  Classes: {CLASS_NAMES}")

"""## 🔍 BƯỚC 4 — Xem mẫu ảnh sau khi crop"""

import matplotlib.pyplot as plt
import matplotlib.image as mpimg
import random
from pathlib import Path

fig, axes = plt.subplots(2, min(4, NUM_CLASSES), figsize=(16, 7))
if NUM_CLASSES == 1:
    axes = axes.reshape(2, 1)
fig.suptitle('🖐️ Mẫu ảnh đã crop theo class', fontsize=14, fontweight='bold')

for col, cls in enumerate(CLASS_NAMES[:4]):
    imgs = list((OUTPUT_DIR / 'train' / cls).glob('*.jpg'))
    sample = random.sample(imgs, min(2, len(imgs)))
    for row, img_path in enumerate(sample):
        img = mpimg.imread(str(img_path))
        axes[row][col].imshow(img)
        axes[row][col].set_title(cls, fontsize=9, fontweight='bold')
        axes[row][col].axis('off')

# Ẩn ô trống
for col in range(NUM_CLASSES, 4):
    for row in range(2):
        axes[row][col].axis('off')

# Đếm số ảnh mỗi class
print("📊 Phân bố dataset:")
for split in ['train', 'valid']:
    split_dir = OUTPUT_DIR / split
    d = {c: len(list((split_dir/c).glob('*.jpg'))) for c in CLASS_NAMES if (split_dir/c).exists()}
    print(f"  {split}: {d}  → tổng {sum(d.values())} ảnh")

plt.tight_layout()
plt.show()

"""## 🧠 BƯỚC 5 — Xây dựng Sequential CNN & Train

Architecture:
```
Input (128×128×3)
 → Conv2D(32) + BN + ReLU + MaxPool
 → Conv2D(64) + BN + ReLU + MaxPool
 → Conv2D(128) + BN + ReLU + MaxPool
 → Conv2D(256) + BN + ReLU + MaxPool
 → GlobalAveragePooling
 → Dense(256) + Dropout(0.4)
 → Dense(N_classes, softmax)
```
"""

import tensorflow as tf
from tensorflow.keras import Sequential, layers, callbacks
from tensorflow.keras.preprocessing.image import ImageDataGenerator
import numpy as np
import matplotlib.pyplot as plt

# ═══════════════════════════════════════════════
# ⚙️  HYPERPARAMETERS
# ═══════════════════════════════════════════════
IMG_SIZE   = 128      # (128, 128) — tăng lên 224 nếu muốn chính xác hơn
BATCH_SIZE = 32
EPOCHS     = 10      # Tăng lên 80–100 nếu dataset nhỏ
LR         = 1e-3
MODEL_PATH = '/content/palm_cnn_sequential.h5'

# ═══════════════════════════════════════════════
# 📦  DATA GENERATORS
# ═══════════════════════════════════════════════
train_gen_cfg = ImageDataGenerator(
    rescale            = 1./255,
    rotation_range     = 20,
    width_shift_range  = 0.15,
    height_shift_range = 0.15,
    shear_range        = 0.1,
    zoom_range         = 0.2,
    horizontal_flip    = True,
    brightness_range   = [0.7, 1.3],
    fill_mode          = 'reflect'
)
val_gen_cfg = ImageDataGenerator(rescale=1./255)

train_gen = train_gen_cfg.flow_from_directory(
    str(OUTPUT_DIR / 'train'),
    target_size = (IMG_SIZE, IMG_SIZE),
    batch_size  = BATCH_SIZE,
    class_mode  = 'categorical',
    shuffle     = True
)
val_gen = val_gen_cfg.flow_from_directory(
    str(OUTPUT_DIR / 'valid'),
    target_size = (IMG_SIZE, IMG_SIZE),
    batch_size  = BATCH_SIZE,
    class_mode  = 'categorical',
    shuffle     = False
)

CLASS_NAMES = list(train_gen.class_indices.keys())
NUM_CLASSES  = len(CLASS_NAMES)
print(f"📚 Classes ({NUM_CLASSES}): {CLASS_NAMES}")
print(f"📊 Train: {train_gen.samples} ảnh | Val: {val_gen.samples} ảnh")

# ═══════════════════════════════════════════════
# 🏗️  XÂY DỰNG SEQUENTIAL CNN
# ═══════════════════════════════════════════════
def build_palm_cnn(input_shape, num_classes):
    model = Sequential(name='PalmLineCNN')

    # ── Block 1: 32 filters ──
    model.add(layers.Input(shape=input_shape))
    model.add(layers.Conv2D(32, (3,3), padding='same', activation='relu'))
    model.add(layers.BatchNormalization())
    model.add(layers.Conv2D(32, (3,3), padding='same', activation='relu'))
    model.add(layers.BatchNormalization())
    model.add(layers.MaxPooling2D(2, 2))
    model.add(layers.Dropout(0.1))

    # ── Block 2: 64 filters ──
    model.add(layers.Conv2D(64, (3,3), padding='same', activation='relu'))
    model.add(layers.BatchNormalization())
    model.add(layers.Conv2D(64, (3,3), padding='same', activation='relu'))
    model.add(layers.BatchNormalization())
    model.add(layers.MaxPooling2D(2, 2))
    model.add(layers.Dropout(0.15))

    # ── Block 3: 128 filters ──
    model.add(layers.Conv2D(128, (3,3), padding='same', activation='relu'))
    model.add(layers.BatchNormalization())
    model.add(layers.Conv2D(128, (3,3), padding='same', activation='relu'))
    model.add(layers.BatchNormalization())
    model.add(layers.MaxPooling2D(2, 2))
    model.add(layers.Dropout(0.2))

    # ── Block 4: 256 filters ──
    model.add(layers.Conv2D(256, (3,3), padding='same', activation='relu'))
    model.add(layers.BatchNormalization())
    model.add(layers.MaxPooling2D(2, 2))
    model.add(layers.Dropout(0.25))

    # ── Classifier head ──
    model.add(layers.GlobalAveragePooling2D())
    model.add(layers.Dense(256, activation='relu'))
    model.add(layers.BatchNormalization())
    model.add(layers.Dropout(0.4))
    model.add(layers.Dense(num_classes, activation='softmax'))

    return model


model = build_palm_cnn((IMG_SIZE, IMG_SIZE, 3), NUM_CLASSES)
model.summary()

# Compile
model.compile(
    optimizer = tf.keras.optimizers.Adam(LR),
    loss      = 'categorical_crossentropy',
    metrics   = ['accuracy']
)
print("\n✅ Model sẵn sàng train!")

# ═══════════════════════════════════════════════
# 🏋️  TRAINING
# ═══════════════════════════════════════════════
cbs = [
    callbacks.ModelCheckpoint(
        MODEL_PATH,
        monitor='val_accuracy', save_best_only=True, verbose=1
    ),
    callbacks.ReduceLROnPlateau(
        monitor='val_loss', factor=0.4, patience=5,
        min_lr=1e-6, verbose=1
    ),
    callbacks.EarlyStopping(
        monitor='val_accuracy', patience=15,
        restore_best_weights=True, verbose=1
    )
]

print(f"🚀 Bắt đầu train {EPOCHS} epochs...")
history = model.fit(
    train_gen,
    epochs          = EPOCHS,
    validation_data = val_gen,
    callbacks       = cbs,
    verbose         = 1
)

best_val_acc = max(history.history['val_accuracy'])
print(f"\n🏆 Best Val Accuracy: {best_val_acc:.1%}")
print(f"💾 Model lưu tại: {MODEL_PATH}")

"""## 📊 BƯỚC 6 — Vẽ biểu đồ kết quả training"""

import matplotlib.pyplot as plt

acc     = history.history['accuracy']
val_acc = history.history['val_accuracy']
loss    = history.history['loss']
val_loss= history.history['val_loss']
eps     = range(1, len(acc)+1)

fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(14, 5))
fig.suptitle('📊 Kết quả Training — Palm Line Sequential CNN', fontsize=14, fontweight='bold')

# Accuracy
ax1.plot(eps, acc,     'b-o', markersize=3, label='Train Acc')
ax1.plot(eps, val_acc, 'r-o', markersize=3, label='Val Acc')
ax1.set_title('🎯 Accuracy'); ax1.set_xlabel('Epoch'); ax1.set_ylabel('Accuracy')
ax1.legend(); ax1.grid(alpha=0.3)
ax1.set_ylim([0, 1])

# Loss
ax2.plot(eps, loss,     'b-o', markersize=3, label='Train Loss')
ax2.plot(eps, val_loss, 'r-o', markersize=3, label='Val Loss')
ax2.set_title('📉 Loss'); ax2.set_xlabel('Epoch'); ax2.set_ylabel('Loss')
ax2.legend(); ax2.grid(alpha=0.3)

plt.tight_layout()
plt.savefig('/content/training_history.png', dpi=130, bbox_inches='tight')
plt.show()
print('✅ Lưu biểu đồ tại /content/training_history.png')

"""## 🎯 BƯỚC 7 — Đánh giá trên tập Test"""

from tensorflow.keras.preprocessing.image import ImageDataGenerator
import numpy as np
from sklearn.metrics import classification_report, confusion_matrix
import matplotlib.pyplot as plt
import seaborn as sns

test_gen_cfg = ImageDataGenerator(rescale=1./255)
test_dir     = OUTPUT_DIR / 'test'

if test_dir.exists() and any(test_dir.iterdir()):
    test_gen = test_gen_cfg.flow_from_directory(
        str(test_dir),
        target_size = (IMG_SIZE, IMG_SIZE),
        batch_size  = BATCH_SIZE,
        class_mode  = 'categorical',
        shuffle     = False
    )

    test_loss, test_acc = model.evaluate(test_gen, verbose=0)
    print(f'📊 Test Accuracy: {test_acc:.1%}  |  Test Loss: {test_loss:.4f}')

    # Classification report
    y_pred = model.predict(test_gen, verbose=0)
    y_pred_cls = y_pred.argmax(axis=1)
    y_true     = test_gen.classes
    print("\n" + classification_report(y_true, y_pred_cls, target_names=CLASS_NAMES))

    # Confusion matrix
    cm = confusion_matrix(y_true, y_pred_cls)
    plt.figure(figsize=(8, 6))
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
                xticklabels=CLASS_NAMES, yticklabels=CLASS_NAMES)
    plt.title('Confusion Matrix'); plt.ylabel('True'); plt.xlabel('Predicted')
    plt.tight_layout()
    plt.savefig('/content/confusion_matrix.png', dpi=130)
    plt.show()
else:
    print('⚠️  Không có tập test riêng — dùng validation để đánh giá.')
    val_loss, val_acc = model.evaluate(val_gen, verbose=0)
    print(f'📊 Val Accuracy: {val_acc:.1%}  |  Val Loss: {val_loss:.4f}')

"""## 🔮 BƯỚC 8 — Hệ thống Đọc Tướng Mệnh/Số"""

# ═══════════════════════════════════════════════════════════════
# 📖 BẢNG TƯỚNG SỐ  (tùy chỉnh theo CLASS_NAMES thực tế)
# ═══════════════════════════════════════════════════════════════
FORTUNE_MAP = {
    "heart": {
        "icon": "❤️",  "name_vi": "Đường Tình Cảm",
        "fortune": "Đường Tình Cảm dài và rõ nét — trái tim nhạy cảm, chân thành. Duyên số đến muộn nhưng bền chặt. Hôn nhân viên mãn sau tuổi 30.",
        "lucky_numbers": [2, 6, 9], "lucky_color": "Đỏ & Hồng 🌸",
        "career": "Giáo viên, tư vấn, y tế, chăm sóc cộng đồng.",
        "wealth": "Tài lộc đến từ mối quan hệ con người."
    },
    "head": {
        "icon": "🧠",  "name_vi": "Đường Trí Tuệ",
        "fortune": "Đường Trí Tuệ thẳng và sâu — tư duy logic, phân tích xuất sắc. Sự nghiệp phát triển rực rỡ sau 35 tuổi nhờ trí óc vượt trội.",
        "lucky_numbers": [1, 4, 7], "lucky_color": "Xanh dương & Vàng 💙",
        "career": "Lập trình, khoa học, tài chính, phân tích dữ liệu.",
        "wealth": "Giàu có nhờ kiến thức và đầu tư thông minh."
    },
    "life": {
        "icon": "🌿",  "name_vi": "Đường Sinh Mệnh",
        "fortune": "Đường Sinh Mệnh cong dài — sức sống dồi dào, sức khỏe tốt đến già. Cuộc đời bình an, ít tai họa bất ngờ.",
        "lucky_numbers": [3, 5, 8], "lucky_color": "Xanh lá & Trắng 🍃",
        "career": "Kinh doanh, bất động sản, nông nghiệp, y tế.",
        "wealth": "Tài sản tích lũy dần, phù hợp đầu tư bất động sản."
    },
    "fate": {
        "icon": "🌟",  "name_vi": "Đường Vận Mệnh",
        "fortune": "Đường Vận Mệnh rõ nét — định hướng rõ ràng, ít lạc lối. Thành công nhờ kiên định. Dễ leo lên vị trí lãnh đạo sau 40.",
        "lucky_numbers": [1, 8, 10], "lucky_color": "Vàng & Tím 💜",
        "career": "Quản lý, lãnh đạo, chính trị, doanh nhân.",
        "wealth": "Giàu có nhờ quyền lực và vị thế xã hội."
    },
    "sun": {
        "icon": "☀️",  "name_vi": "Đường Mặt Trời",
        "fortune": "Đường Mặt Trời xuất hiện — tài năng nghệ thuật vượt trội, có khả năng nổi tiếng. Sung túc sau 35 tuổi. Quý nhân phù trợ mạnh.",
        "lucky_numbers": [5, 6, 11], "lucky_color": "Cam & Vàng 🧡",
        "career": "Nghệ thuật, giải trí, truyền thông, sáng tạo nội dung.",
        "wealth": "Thu nhập tăng vọt khi nổi tiếng."
    },
    "mercury": {
        "icon": "💬",  "name_vi": "Đường Thủy Ngân",
        "fortune": "Đường Thủy Ngân rõ nét — giao tiếp xuất sắc, thực tế, nhạy bén thương mại. Tài chính tăng trưởng đều đặn.",
        "lucky_numbers": [3, 7, 12], "lucky_color": "Bạc & Xanh nhạt 🩵",
        "career": "Thương mại, marketing, luật, môi giới.",
        "wealth": "Giỏi kiếm tiền và quản lý. Phù hợp kinh doanh đa lĩnh vực."
    },
    "marriage": {
        "icon": "💍",  "name_vi": "Đường Hôn Nhân",
        "fortune": "Đường Hôn Nhân dài và rõ — hôn nhân hạnh phúc, bền lâu. Người bạn đời là nguồn sức mạnh tinh thần lớn.",
        "lucky_numbers": [2, 4, 6], "lucky_color": "Hồng & Trắng 🤍",
        "career": "Gia đình là động lực lớn nhất, phù hợp mọi ngành.",
        "wealth": "Tài lộc đến từ hợp tác vợ chồng, gia nghiệp thịnh vượng."
    },
    "health": {
        "icon": "💚",  "name_vi": "Đường Sức Khỏe",
        "fortune": "Đường Sức Khỏe xuất hiện — cần chú ý ăn uống và nghỉ ngơi. Sức khỏe là nền tảng thành công.",
        "lucky_numbers": [5, 7, 9], "lucky_color": "Xanh lá & Vàng 💛",
        "career": "Y tế, thể thao, dinh dưỡng, yoga.",
        "wealth": "Sức khỏe tốt mang lại tài lộc, không nên làm việc quá sức."
    },
    "default": {
        "icon": "🖐️",  "name_vi": "Đường Chỉ Đặc Biệt",
        "fortune": "Bàn tay bạn có đường chỉ đặc biệt hiếm gặp. Cuộc đời nhiều biến đổi bất ngờ, nhưng bạn luôn tìm được cơ hội mới nhờ sự linh hoạt.",
        "lucky_numbers": [6, 8, 9], "lucky_color": "Xanh lam & Trắng 🤍",
        "career": "Đa năng, phù hợp công việc sáng tạo và tự do.",
        "wealth": "Tài lộc đến từ nhiều hướng — linh hoạt là chìa khóa."
    }
}

def get_fortune(class_name: str) -> dict:
    cn = class_name.lower().strip()
    for key in FORTUNE_MAP:
        if key != 'default' and (key in cn or cn in key):
            return FORTUNE_MAP[key]
    kw_map = {
        'tim':'heart','love':'heart','emotion':'heart',
        'brain':'head','mind':'head','tri':'head',
        'sinh':'life','vitality':'life',
        'destiny':'fate','fate':'fate','saturn':'fate',
        'apollo':'sun','creative':'sun',
        'business':'mercury','comm':'mercury',
        'marriage':'marriage','union':'marriage','love_line':'marriage',
        'health':'health','suc':'health',
    }
    for kw, mapped in kw_map.items():
        if kw in cn:
            return FORTUNE_MAP[mapped]
    return FORTUNE_MAP['default']

print('✅ Hệ thống đọc tướng sẵn sàng!')

"""## 🔮 BƯỚC 9 — Hàm Predict & Hiển thị kết quả"""

import numpy as np
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
from tensorflow.keras.preprocessing import image as keras_image
from tensorflow.keras.models import load_model
from PIL import Image

# Load best model
best_model = load_model(MODEL_PATH)
print(f'✅ Loaded model: {MODEL_PATH}')


def predict_fortune(img_path: str, top_k: int = 3):
    """Nhận diện đường chỉ tay + đọc tướng"""
    # Tiền xử lý
    img      = Image.open(img_path).convert('RGB')
    img_arr  = img.resize((IMG_SIZE, IMG_SIZE))
    x        = keras_image.img_to_array(img_arr) / 255.0
    x        = np.expand_dims(x, axis=0)

    probs    = best_model.predict(x, verbose=0)[0]
    top_idxs = probs.argsort()[::-1][:top_k]

    results  = [{"class": CLASS_NAMES[i], "prob": probs[i]} for i in top_idxs]
    fortune  = get_fortune(results[0]['class'])
    return img, results, fortune


def show_fortune(img_path: str):
    """Hiển thị ảnh + kết quả đọc tướng"""
    img, results, fortune = predict_fortune(img_path)

    fig = plt.figure(figsize=(16, 7), facecolor='#1a1a2e')

    # ── Ảnh gốc ──
    ax_img = fig.add_axes([0.01, 0.04, 0.40, 0.90])
    ax_img.imshow(img)
    ax_img.set_title('🖐️ Ảnh bàn tay của bạn',
                     color='white', fontsize=12, fontweight='bold', pad=8)
    ax_img.axis('off')

    # ── Bar chart top-K ──
    ax_bar = fig.add_axes([0.44, 0.60, 0.24, 0.32])
    labels = [r['class'] for r in results]
    probs  = [r['prob']*100 for r in results]
    colors = ['#FF6B6B'] + ['#74B9FF']*(len(results)-1)
    bars   = ax_bar.barh(labels, probs, color=colors, edgecolor='none', height=0.5)
    for bar, p in zip(bars, probs):
        ax_bar.text(bar.get_width()+0.5, bar.get_y()+bar.get_height()/2,
                    f'{p:.1f}%', va='center', fontsize=9, color='white')
    ax_bar.set_facecolor('#2d2d5e')
    ax_bar.tick_params(colors='white'); ax_bar.set_xlim(0, 115)
    ax_bar.set_title('🎯 Top dự đoán', color='white', fontsize=10)
    ax_bar.invert_yaxis()
    for spine in ax_bar.spines.values(): spine.set_visible(False)

    # ── Tướng số ──
    ax_txt = fig.add_axes([0.44, 0.04, 0.54, 0.52])
    ax_txt.axis('off')
    ax_txt.set_facecolor('#2d2d5e')

    top    = results[0]
    nums   = '   ·   '.join(f'🔢 {n}' for n in fortune['lucky_numbers'])
    header = f"{fortune['icon']}  {fortune['name_vi'].upper()}  {fortune['icon']}"

    ax_txt.text(0.5, 0.99, header, transform=ax_txt.transAxes,
                fontsize=15, fontweight='bold', color='#FFE66D',
                ha='center', va='top')
    ax_txt.text(0.5, 0.89, f"Độ tin cậy: {top['prob']:.1%}",
                transform=ax_txt.transAxes, fontsize=11, color='#6BCB77',
                ha='center', va='top')

    lines = [
        (0.74, '📜 Tướng số:', '#FF9F1C', 10, 'bold'),
        (0.63, fortune['fortune'], 'white', 9, 'normal'),
        (0.36, f"💼 {fortune['career']}", '#74B9FF', 9, 'normal'),
        (0.22, f"💰 {fortune['wealth']}", '#B2FF59', 9, 'normal'),
        (0.10, f"🎨 Màu may mắn: {fortune['lucky_color']}", '#FF80AB', 9, 'normal'),
    ]
    for y, txt, col, fs, fw in lines:
        ax_txt.text(0.03, y, txt, transform=ax_txt.transAxes,
                    fontsize=fs, color=col, fontweight=fw, va='top')

    # Lucky numbers strip
    ax_num = fig.add_axes([0.70, 0.60, 0.28, 0.32])
    ax_num.axis('off'); ax_num.set_facecolor('#2d2d5e')
    ax_num.text(0.5, 0.72, '🍀 Con số may mắn',
                transform=ax_num.transAxes, ha='center',
                fontsize=10, color='#FFE66D', fontweight='bold')
    ax_num.text(0.5, 0.25, nums, transform=ax_num.transAxes,
                ha='center', fontsize=13, color='white', fontweight='bold')

    plt.suptitle('🔮  MÁY ĐỌC TƯỚNG CHỈ TAY AI — Sequential CNN  🔮',
                 fontsize=14, fontweight='bold', color='#E040FB', y=0.99)

    out = '/content/fortune_result.png'
    plt.savefig(out, dpi=150, bbox_inches='tight', facecolor='#1a1a2e')
    plt.show()
    print(f'\n💾 Lưu kết quả: {out}')

print('✅ Hàm predict sẵn sàng! Chạy Bước 10 để upload ảnh.')

"""## 📤 BƯỚC 10 — Upload ảnh bàn tay → Đọc tướng!

> 💡 **Mẹo:** Xòe rộng bàn tay, ánh sáng đều từ trên xuống, nền trắng/sáng, tránh bóng đổ
"""

from google.colab import files

print('📂 Chọn ảnh bàn tay để đọc tướng...')
uploaded = files.upload()

for filename in uploaded.keys():
    print(f'\n🔮 Đang phân tích: {filename}')
    show_fortune(filename)

    # In kết quả text
    img, results, fortune = predict_fortune(filename)
    print('\n' + '═'*50)
    print(f'{fortune["icon"]}  {fortune["name_vi"]}  |  Độ tin cậy: {results[0]["prob"]:.1%}')
    print('─'*50)
    print(f'📜 {fortune["fortune"]}')
    print(f'💼 {fortune["career"]}')
    print(f'💰 {fortune["wealth"]}')
    print(f'🔢 Con số may mắn: {fortune["lucky_numbers"]}')
    print(f'🎨 Màu may mắn:   {fortune["lucky_color"]}')
    print('═'*50)

"""## 🧪 BƯỚC 11 (Tùy chọn) — Test trên ảnh validation"""

import random
from pathlib import Path

val_imgs = list((OUTPUT_DIR / 'valid').rglob('*.jpg'))
sample   = random.sample(val_imgs, min(3, len(val_imgs)))

for p in sample:
    print(f'\n📸 {p.name}  (class gốc: {p.parent.name})')
    show_fortune(str(p))

"""## 💾 BƯỚC 12 — Download model"""

from google.colab import files
import json

# Lưu class names kèm model
meta = {'class_names': CLASS_NAMES, 'img_size': IMG_SIZE}
with open('/content/palm_cnn_meta.json', 'w') as f:
    json.dump(meta, f)

files.download(MODEL_PATH)
files.download('/content/palm_cnn_meta.json')
files.download('/content/training_history.png')
print('✅ Done!')

print('\n📌 Cách dùng lại model:')
print('  from tensorflow.keras.models import load_model')
print('  model = load_model("palm_cnn_sequential.h5")')

model.save(MODEL_PATH)
print(f'✅ Model saved to: {MODEL_PATH}')